# pipenv install investpy

DEBUG_MODE = True
WRITE_REQUEST_TO_FILE = True

# PANDAS_TA Period Values
TA_PERIOD_1D = "1d"
TA_PERIOD_5D = "5d"
TA_PERIOD_1MO = "1mo"
TA_PERIOD_3MO = "3mo"
TA_PERIOD_6MO = "6mo"
TA_PERIOD_1Y = "1y"
TA_PERIOD_2Y = "2y"
TA_PERIOD_5Y = "5y"
TA_PERIOD_10Y = "10y"
TA_PERIOD_YTD = "ytd"
TA_PERIOD_MAX = "max"
TA_PERIODS = [TA_PERIOD_1D, TA_PERIOD_5D, TA_PERIOD_1MO, TA_PERIOD_3MO,
              TA_PERIOD_6MO, TA_PERIOD_1Y, TA_PERIOD_2Y, TA_PERIOD_5Y,
              TA_PERIOD_10Y, TA_PERIOD_YTD, TA_PERIOD_MAX]

# PANDAS_TA Interval Values
TA_INTERVAL_5M = "5m"
TA_INTERVAL_15M = "15m"
TA_INTERVAL_30M = "30m"
TA_INTERVAL_1H = "1h"
TA_INTERVAL_4H = "4h"
TA_INTERVAL_1D = "1d"
TA_INTERVAL_1WK = "1w"
TA_INTERVALS = [TA_INTERVAL_5M, TA_INTERVAL_15M, TA_INTERVAL_30M, TA_INTERVAL_1H, 
                TA_INTERVAL_4H, TA_INTERVAL_1D, TA_INTERVAL_1WK]

# Signal Values
STRONG_BUY = 'Strong Buy'
BUY = 'Buy'
STRONG_SELL = 'Strong Sell'
SELL = 'Sell'

# Direction Values
LONG = 'LONG'
SHORT = 'SHORT'

# CCI Area Values
TOP_TOP = 'TT'
TOP_MIDDLE = 'TM'
MIDDLE_TOP = 'MT'
MIDDLE_MIDDLE = 'MM'
MIDDLE_BELOW = 'MB'
BELOW_MIDDLE = 'BM'
BELOW_BELOW = 'BB'

# Column Names
SIGNAL = 'Signal'
AREA = 'Area'

# Order Statuses
ORDER_STATUS_OPEN = 'Open'
ORDER_STATUS_CLOSE = 'Close'

# Order Close Reason
ORDER_CLOSE_REASON_STOP_LOSS = 'Stop Loss'
ORDER_CLOSE_REASON_TAKE_PROFIT = 'Take Profit'
ORDER_CLOSE_REASON_SIGNAL = 'Signal'
